# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import server_services_pb2 as server__services__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in server_services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CarServiceStub(object):
    """Service definition for car-related operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllCars = channel.unary_unary(
                '/cars.CarService/GetAllCars',
                request_serializer=server__services__pb2.GetAllCarsRequest.SerializeToString,
                response_deserializer=server__services__pb2.GetAllCarsResponse.FromString,
                _registered_method=True)
        self.GetCarsByMakeModel = channel.unary_unary(
                '/cars.CarService/GetCarsByMakeModel',
                request_serializer=server__services__pb2.GetCarsByMakeModelRequest.SerializeToString,
                response_deserializer=server__services__pb2.GetCarsByMakeModelResponse.FromString,
                _registered_method=True)
        self.GetCarsByPriceRange = channel.unary_unary(
                '/cars.CarService/GetCarsByPriceRange',
                request_serializer=server__services__pb2.GetCarsByPriceRangeRequest.SerializeToString,
                response_deserializer=server__services__pb2.GetCarsByPriceRangeResponse.FromString,
                _registered_method=True)
        self.GetCarsByYearCondition = channel.unary_unary(
                '/cars.CarService/GetCarsByYearCondition',
                request_serializer=server__services__pb2.GetCarsByYearConditionRequest.SerializeToString,
                response_deserializer=server__services__pb2.GetCarsByYearConditionResponse.FromString,
                _registered_method=True)
        self.AddCar = channel.unary_unary(
                '/cars.CarService/AddCar',
                request_serializer=server__services__pb2.AddCarRequest.SerializeToString,
                response_deserializer=server__services__pb2.AddCarResponse.FromString,
                _registered_method=True)


class CarServiceServicer(object):
    """Service definition for car-related operations
    """

    def GetAllCars(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCarsByMakeModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCarsByPriceRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCarsByYearCondition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddCar(self, request, context):
        """AddCar RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllCars': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllCars,
                    request_deserializer=server__services__pb2.GetAllCarsRequest.FromString,
                    response_serializer=server__services__pb2.GetAllCarsResponse.SerializeToString,
            ),
            'GetCarsByMakeModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCarsByMakeModel,
                    request_deserializer=server__services__pb2.GetCarsByMakeModelRequest.FromString,
                    response_serializer=server__services__pb2.GetCarsByMakeModelResponse.SerializeToString,
            ),
            'GetCarsByPriceRange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCarsByPriceRange,
                    request_deserializer=server__services__pb2.GetCarsByPriceRangeRequest.FromString,
                    response_serializer=server__services__pb2.GetCarsByPriceRangeResponse.SerializeToString,
            ),
            'GetCarsByYearCondition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCarsByYearCondition,
                    request_deserializer=server__services__pb2.GetCarsByYearConditionRequest.FromString,
                    response_serializer=server__services__pb2.GetCarsByYearConditionResponse.SerializeToString,
            ),
            'AddCar': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCar,
                    request_deserializer=server__services__pb2.AddCarRequest.FromString,
                    response_serializer=server__services__pb2.AddCarResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cars.CarService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cars.CarService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CarService(object):
    """Service definition for car-related operations
    """

    @staticmethod
    def GetAllCars(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cars.CarService/GetAllCars',
            server__services__pb2.GetAllCarsRequest.SerializeToString,
            server__services__pb2.GetAllCarsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCarsByMakeModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cars.CarService/GetCarsByMakeModel',
            server__services__pb2.GetCarsByMakeModelRequest.SerializeToString,
            server__services__pb2.GetCarsByMakeModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCarsByPriceRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cars.CarService/GetCarsByPriceRange',
            server__services__pb2.GetCarsByPriceRangeRequest.SerializeToString,
            server__services__pb2.GetCarsByPriceRangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCarsByYearCondition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cars.CarService/GetCarsByYearCondition',
            server__services__pb2.GetCarsByYearConditionRequest.SerializeToString,
            server__services__pb2.GetCarsByYearConditionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddCar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cars.CarService/AddCar',
            server__services__pb2.AddCarRequest.SerializeToString,
            server__services__pb2.AddCarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SendFileServiceStub(object):
    """Service definition for file sending operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendFile = channel.unary_unary(
                '/cars.SendFileService/SendFile',
                request_serializer=server__services__pb2.SendFileRequestBody.SerializeToString,
                response_deserializer=server__services__pb2.SendFileResponseBody.FromString,
                _registered_method=True)
        self.SendFileChunks = channel.stream_unary(
                '/cars.SendFileService/SendFileChunks',
                request_serializer=server__services__pb2.SendFileChunksRequest.SerializeToString,
                response_deserializer=server__services__pb2.SendFileChunksResponse.FromString,
                _registered_method=True)


class SendFileServiceServicer(object):
    """Service definition for file sending operations
    """

    def SendFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFileChunks(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SendFileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendFile': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFile,
                    request_deserializer=server__services__pb2.SendFileRequestBody.FromString,
                    response_serializer=server__services__pb2.SendFileResponseBody.SerializeToString,
            ),
            'SendFileChunks': grpc.stream_unary_rpc_method_handler(
                    servicer.SendFileChunks,
                    request_deserializer=server__services__pb2.SendFileChunksRequest.FromString,
                    response_serializer=server__services__pb2.SendFileChunksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cars.SendFileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cars.SendFileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SendFileService(object):
    """Service definition for file sending operations
    """

    @staticmethod
    def SendFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cars.SendFileService/SendFile',
            server__services__pb2.SendFileRequestBody.SerializeToString,
            server__services__pb2.SendFileResponseBody.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendFileChunks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/cars.SendFileService/SendFileChunks',
            server__services__pb2.SendFileChunksRequest.SerializeToString,
            server__services__pb2.SendFileChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CarServiceDatabaseStub(object):
    """Service definition for car database operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllCars = channel.unary_unary(
                '/cars.CarServiceDatabase/GetAllCars',
                request_serializer=server__services__pb2.GetAllCarsRequest.SerializeToString,
                response_deserializer=server__services__pb2.GetAllCarsResponse.FromString,
                _registered_method=True)
        self.AddCar = channel.unary_unary(
                '/cars.CarServiceDatabase/AddCar',
                request_serializer=server__services__pb2.AddCarRequest.SerializeToString,
                response_deserializer=server__services__pb2.AddCarResponse.FromString,
                _registered_method=True)
        self.UpdateCar = channel.unary_unary(
                '/cars.CarServiceDatabase/UpdateCar',
                request_serializer=server__services__pb2.UpdateCarRequest.SerializeToString,
                response_deserializer=server__services__pb2.UpdateCarResponse.FromString,
                _registered_method=True)
        self.DeleteCar = channel.unary_unary(
                '/cars.CarServiceDatabase/DeleteCar',
                request_serializer=server__services__pb2.DeleteCarRequest.SerializeToString,
                response_deserializer=server__services__pb2.DeleteCarResponse.FromString,
                _registered_method=True)
        self.GetCarByVin = channel.unary_unary(
                '/cars.CarServiceDatabase/GetCarByVin',
                request_serializer=server__services__pb2.GetCarByVinRequest.SerializeToString,
                response_deserializer=server__services__pb2.GetCarByVinResponse.FromString,
                _registered_method=True)


class CarServiceDatabaseServicer(object):
    """Service definition for car database operations
    """

    def GetAllCars(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddCar(self, request, context):
        """AddCar RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCarByVin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarServiceDatabaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllCars': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllCars,
                    request_deserializer=server__services__pb2.GetAllCarsRequest.FromString,
                    response_serializer=server__services__pb2.GetAllCarsResponse.SerializeToString,
            ),
            'AddCar': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCar,
                    request_deserializer=server__services__pb2.AddCarRequest.FromString,
                    response_serializer=server__services__pb2.AddCarResponse.SerializeToString,
            ),
            'UpdateCar': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCar,
                    request_deserializer=server__services__pb2.UpdateCarRequest.FromString,
                    response_serializer=server__services__pb2.UpdateCarResponse.SerializeToString,
            ),
            'DeleteCar': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCar,
                    request_deserializer=server__services__pb2.DeleteCarRequest.FromString,
                    response_serializer=server__services__pb2.DeleteCarResponse.SerializeToString,
            ),
            'GetCarByVin': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCarByVin,
                    request_deserializer=server__services__pb2.GetCarByVinRequest.FromString,
                    response_serializer=server__services__pb2.GetCarByVinResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cars.CarServiceDatabase', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cars.CarServiceDatabase', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CarServiceDatabase(object):
    """Service definition for car database operations
    """

    @staticmethod
    def GetAllCars(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cars.CarServiceDatabase/GetAllCars',
            server__services__pb2.GetAllCarsRequest.SerializeToString,
            server__services__pb2.GetAllCarsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddCar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cars.CarServiceDatabase/AddCar',
            server__services__pb2.AddCarRequest.SerializeToString,
            server__services__pb2.AddCarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cars.CarServiceDatabase/UpdateCar',
            server__services__pb2.UpdateCarRequest.SerializeToString,
            server__services__pb2.UpdateCarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cars.CarServiceDatabase/DeleteCar',
            server__services__pb2.DeleteCarRequest.SerializeToString,
            server__services__pb2.DeleteCarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCarByVin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cars.CarServiceDatabase/GetCarByVin',
            server__services__pb2.GetCarByVinRequest.SerializeToString,
            server__services__pb2.GetCarByVinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
